site_name: Skeleton app
site_url: https://conductionnl.github.io/skeleton-app
docs_dir: docs
nav:
    - Introduction skeleton-app: index.md
    - The layout: layout.md
    - Adding pages: pages.md
    - Components: components.md
theme:
    name: readthedocs